"""
Qubit-reuse-optimal compilation of the diamond structured quantum circuit.
"""

import numpy
from functools import reduce
from quantum.circuit import Circuit

# Since dynamic circuit compilation is independent of the type of two-qubit gates,
# all two-qubit gates are implemented as controlled-NOT gates.

# Set the number of qubits (even number)
n = 4
qubit_num = 2 * n

# Create a quantum circuit
cir = Circuit("Diamond structured circuit")

# Construct the diamond structured circuit
for i in range(0, n):
    cir.x(i)
# Double-qubit rotation gates
for j in range(n):
    for k in range(n - j - 1, n + j, 2):
        cir.cx([k, k + 1])
for j in range(n - 1, 0, -1):
    for k in range(n - j, n + j - 1, 2):
        cir.cx([k, k + 1])

# Measure all qubits
cir.measure()
# Print quantum circuit
cir.print_circuit()


# Get the biadjacency matrix and the candidate matrix of the simplified graph
# of the quantum circuit through boolean matrix multiplication
b_circuit, c_circuit = cir.get_biadjacency_and_candidate_matrices(method="boolean_matrix")

# Construct the biadjacency matrix based on theoretical analysis.
b_theory = numpy.zeros((qubit_num, qubit_num), dtype=int)
for i in range(0, n):
    for j in range(0, i + n + 1):
        b_theory[i][j] += 1
for i in range(n, 2 * n):
    for j in range(i - n, 2 * n):
        b_theory[i][j] += 1

# Verify if two biadjacency matrices generated by different approaches are identical
b_difference = b_circuit - b_theory
print("\nThe biadjacency matrices generated by different approaches are identical:", numpy.all(b_difference == 0))

# Construct the candidate matrix based on theoretical analysis.
c_theory = numpy.zeros((qubit_num, qubit_num), dtype=int)
for i in range(n + 1, 2 * n):
    for j in range(0, i - n):
        c_theory[i][j] += 1
for i in range(0, n - 1):
    for j in range(i + n + 1, 2 * n):
        c_theory[i][j] += 1

# Verify if two candidate matrices generated by different approaches are identical
c_difference = c_circuit - c_theory
print("\nThe candidate matrices generated by different approaches are identical:", numpy.all(c_difference == 0))


# Construct the matrix corresponding to the added edges in the optimal compilation
op_matrix = numpy.zeros([qubit_num, qubit_num], dtype=int)
for i in range(0, n - 1):
    op_matrix[i][i + n + 1] += 1

# Construct the adjacency matrix corresponding to the optimal compilation
zero_matrix = numpy.zeros([qubit_num, qubit_num], dtype=int)
adjacency_matrix = numpy.block([[zero_matrix, b_circuit], [op_matrix, zero_matrix]])

# Iteratively calculate the power of the adjacency matrix
nilpotent = reduce(numpy.matmul, [adjacency_matrix for _ in range(2 * qubit_num)])

# Check whether the adjacency matrix corresponding to the optimal compilation is nilpotent
print("\nThe adjacency matrix corresponding to the optimal compilation is nilpotent:", numpy.all(nilpotent == 0))
